spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_smart?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 178290
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#  mvc:
#    view:
#      prefix: /
logging:
  level:
    root: warn

  file: log/blog-dev.log
server:
  port: 80